language: ruby
rvm:
  - 2.2.4

install: gem install jekyll jekyll-paginate html-proofer

script: jekyll build && htmlproofer

branches:
  only:
    - gh-pages
    - /pages-(.*)/

env:
  global:
    -NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
