
title: Norman Chan
email: slowmanchan@gmail.com
description: >
  Full stack developer, portfolio, freelance, Ruby on Rails specialty, Toronto ON.
baseurl: "/homepage-jekyll" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: slowmanchan
github_username:  slowmanchan

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock

#sass
sass:
  style: compressed
