title: Norman Chan
email: slowmanchan@gmail.com
description: >
  Full stack developer, portfolio, freelance, Ruby on Rails specialty, Toronto ON.
baseurl: "" # the subpath of your site, e.g. /blog
excerpt_separator: <!--more-->
url: "https://slowmanchan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: slowmanchan
github_username:  slowmanchan

# Build settings
markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "fenced_code_blocks", "with_toc_data"]
theme: minima
gems:
  - jekyll-feed

include: ['_pages']
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
#sass
sass:
  style: compressed
